import Head from "next/head";
import Image from "next/image";
import Ashoka from "../../public/ashoka.png";
import Navbar from "../../components/navbar/navbar";
import { useRouter } from "next/router";

export default function CitizenLogin() {
  const router = useRouter();

  return (
    <div>
      <Navbar />
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row" style={{ height: "100vh", margin: 0 }}>
        <div className="col-12 d-flex flex-column justify-content-center px-20">
          <div className="d-flex justify-content-center">
            <Image src={Ashoka} className="img-fluid" height={200} />
          </div>
          <div className="d-flex justify-content-center">
            <form>
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">
                  Username
                </label>
                <input
                  type="email"
                  class="form-control"
                  aria-describedby="emailHelp"
                />
              </div>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">
                  Password
                </label>
                <input type="password" class="form-control" />
              </div>
              <div class="mb-3">
                <select>
                  <option value="Over Speeding">Citizen</option>
                  <option value="Police">Police</option>
                  <option value="Hospital">Hospital</option>
                  <option value="Ambulance">Ambulance</option>
                  <option value="PWD B&R">PWD B&R</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary">
                Submit
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
