import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import Ashoka from "../../public/ashoka.png";
import Navbar from "../../components/navbar/navbar";
import { useRouter } from "next/router";
import userApi from "../api/user";

export default function CitizenLogin() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [userType, setUserType] = useState("citizen");
  const router = useRouter();

  useEffect(() => {
    let token = localStorage.getItem('token');
    let user = localStorage.getItem('user');
    if(token && user) {
        router.push("/dashboard");
    }
    return () => {}
  }, []);

  const submit = async(e) => {
    e.preventDefault();
    let res = await userApi.login({ username, password, type: userType });
    if(!res.error) {
        localStorage.setItem(`token`, res.token);
        localStorage.setItem('user', JSON.stringify(res.data));
        router.push("/dashboard");
    }
  }

  return (
    <div>
      <Navbar />
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row" style={{ height: "100vh", margin: 0 }}>
        <div className="col-12 d-flex flex-column justify-content-center px-20">
          <div className="d-flex justify-content-center">
            <Image src={Ashoka} className="img-fluid" height={200} />
          </div>
          <div className="d-flex justify-content-center">
            <form>
              <div className="mb-3">
                <label for="exampleInputEmail1" className="form-label">
                  Username
                </label>
                <input
                  type="text"
                  className="form-control"
                  aria-describedby="emailHelp"
                  onChange={(e) => setUsername(e.target.value)}
                />
              </div>
              <div className="mb-3">
                <label for="exampleInputPassword1" className="form-label">
                  Password
                </label>
                <input type="password" className="form-control" onChange={(e) => setPassword(e.target.value)} />
              </div>
              <div className="mb-3">
                <select onChange={(e) => setUserType(e.target.value)}>
                  <option value="citizen">Citizen</option>
                  <option value="police">Police</option>
                  <option value="hospital">Hospital</option>
                  <option value="ambulance">Ambulance</option>
                  <option value="roadAgency">PWD B&R</option>
                </select>
              </div>
              <button type="submit" className="btn btn-primary" onClick={submit}>
                Submit
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
