import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Ashoka from "../public/ashoka.png";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Road Guardian</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ marginTop: 50 }}>
        <div className="col-12 d-flex flex-column justify-content-center px-20">
          <div className="d-flex justify-content-center">
            <Image src={Ashoka} className="img-fluid" height={200} />
          </div>
          <div className="d-flex justify-content-center flex-column text-center">
            <h1 style={{ fontFamily: "Poppins" }}>
              <b>Road Guardian</b>
            </h1>
            <h6 className="my-30" style={{ fontFamily: "Poppins" }}>
              Empowering citizens to create safer roads: Report hazards,
              accidents, and unsafe driving behavior with our citizen portal
              app.
            </h6>
          </div>
          <div className="d-flex justify-content-center my-2">
            <button
              type="button"
              className="btn btn-warning mx-2 w-50"
              onClick={() => router.push("/login")}
            >
              Access Portal
            </button>
          </div>
        </div>
        <div className="container" style={{ marginTop: 30 }}>
          <h2 className="text-center"><b>Citizen Portal App</b></h2>
          <h5 className="text-center">
            A citizen portal app can be a useful tool for mitigating road safety
            issues by empowering citizens to report hazards, accidents, and
            unsafe driving behavior. Here are some ideas for features that could
            be included in such an app:
          </h5>
          <div style={{marginTop: 40, border: "2px dashed black", padding: "20px"}}>
            <p>
              <b>1. Hazard reporting: </b>Citizens can use the app to report hazards such
              as potholes, debris on the road, and malfunctioning traffic
              lights. The app can use GPS to automatically identify the location
              of the hazard and allow citizens to attach photos or videos to the
              report.
            </p>
            <p>
              <b>2. Accident reporting: </b>Citizens can report accidents they witness,
              including the location, the number of vehicles involved, and any
              injuries. The app can use GPS to automatically identify the
              location of the accident and allow citizens to attach photos or
              videos to the report.
            </p>
            <p>
              <b>3. Unsafe driving behavior reporting: </b>Citizens can report unsafe
              driving behavior they witness, such as speeding, distracted
              driving, or aggressive driving. The app can use GPS to
              automatically identify the location and allow citizens to attach
              photos or videos to the report.
            </p>

            <p>
              <b>4. Gamification: </b>The app can incorporate gamification elements to
              incentivize safe driving behaviors. For example, users can earn
              points for reporting hazards, accidents, and unsafe driving
              behaviors, which can be redeemed for prizes or discounts.
            </p>

            <p>
              <b>5. Emergency services integration: </b>The app can include integration
              with emergency services such as ambulance, police, and fire
              services, to enable quick responses to accidents or hazards.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
