import Head from "next/head";
import Image from "next/image";
import Ashoka from "../../public/ashoka.png";
import Navbar from "../../components/navbar/navbar";
import { useRouter } from "next/router";

export default function Dashboard() {
  const router = useRouter();

  return (
    <div>
      <Navbar />
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row" style={{ height: "100vh", margin: 0 }}>
        <div className="col-12 d-flex flex-column justify-content-center px-20">
          <div className="d-flex justify-content-center">
            <Image src={Ashoka} className="img-fluid" height={200} />
          </div>
          <div className="d-flex justify-content-center flex-column text-center">
            <h1 style={{ fontFamily: "Poppins" }}>
              <b>Road Guardian</b>
            </h1>
            <h6 className="my-30" style={{ fontFamily: "Poppins" }}>
              Empowering citizens to create safer roads: Report hazards,
              accidents, and unsafe driving behavior with our citizen portal
              app.
            </h6>
          </div>
          <div className="d-flex justify-content-center my-2">
            <button
              type="button"
              className="btn btn-warning mx-2 w-50"
              style={{ fontFamily: "Poppins" }}
              onClick={() => router.push("/report/accident")}
            >
              Report Accident
            </button>
          </div>
          <div className="d-flex justify-content-center my-2">
            <button type="button" className="btn btn-primary mx-2 w-50">
              Report Hazard
            </button>
          </div>
          <div className="d-flex justify-content-center my-2">
            <button
              type="button"
              className="btn btn-danger mx-2 w-50"
              style={{ fontFamily: "Poppins" }}
            >
              Report Bad Driving
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
